# Default values for cvibe-hub

replicaCount: 1

image:
  repository: cvibe-hub
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
podAnnotations: {}

serviceAccount:
  create: true
  annotations: {}
  name: "cvibe-hub"

podSecurityContext:
  fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

env: {}
secrets: {}

healthCheck:
  enabled: true
  livenessProbe:
    httpGet:
      path: /api/health
      port: http
    initialDelaySeconds: 30
    periodSeconds: 60
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /api/health
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

# Production-only features disabled by default
podDisruptionBudget:
  enabled: false

networkPolicy:
  enabled: false

# ServiceMonitor disabled by default (Prometheus Operator not always available)
serviceMonitor:
  enabled: false

externalSecrets:
  enabled: false
  refreshInterval: "1m"
  gcpServiceAccount: ""
  serviceAccount:
    create: false
    annotations: {}
    name: ""

# GCP configuration (production only)
gcp:
  projectId: "cvibe-471219"
  clusterLocation: "us-east1"
  clusterName: "cvibe-prod"
